
services:
  db:
    image: postgres:15-alpine
    container_name: gestor_db
    environment:
      POSTGRES_DB: gestor
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: gestor_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestor
      SPRING_DATASOURCE_USERNAME: gestor
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_MVC_HIDDENMETHOD_FILTER_ENABLED: true
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
